# Generated by Django 6.1 on 2026-08-18 09:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_contentblock_description_en_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contentblock',
            options={'ordering': ['order', 'created_at'], 'verbose_name': 'Блок контента', 'verbose_name_plural': 'Блоки контента'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-created_at'], 'verbose_name': 'Проект', 'verbose_name_plural': 'Проекты'},
        ),
        migrations.AlterField(
            model_name='contentblock',
            name='content_type',
            field=models.CharField(choices=[('image', 'Изображение'), ('video', 'Видео'), ('text', 'Текст'), ('pdf', 'PDF'), ('link', 'Ссылка')], default='image', max_length=20, verbose_name='Тип контента'),
        ),
        migrations.AlterField(
            model_name='contentblock',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='contentblock',
            name='description',
            field=models.TextField(blank=True, verbose_name='Текст / Описание'),
        ),
        migrations.AlterField(
            model_name='contentblock',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Текст / Описание'),
        ),
        migrations.AlterField(
            model_name='contentblock',
            name='description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Текст / Описание'),
        ),
        migrations.AlterField(
            model_name='contentblock',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='projects/files/', verbose_name='Файл (PDF)'),
        ),
        migrations.AlterField(
            model_name='contentblock',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='projects/images/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='contentblock',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Порядок отображения'),
        ),
        migrations.AlterField(
            model_name='contentblock',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_blocks', to='portfolio.project', verbose_name='Проект'),
        ),
        migrations.AlterField(
            model_name='contentblock',
            name='title',
            field=models.CharField(blank=True, max_length=200, verbose_name='Заголовок блока'),
        ),
        migrations.AlterField(
            model_name='contentblock',
            name='title_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Заголовок блока'),
        ),
        migrations.AlterField(
            model_name='contentblock',
            name='title_ru',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Заголовок блока'),
        ),
        migrations.AlterField(
            model_name='contentblock',
            name='url',
            field=models.URLField(blank=True, verbose_name='Ссылка'),
        ),
        migrations.AlterField(
            model_name='contentblock',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='projects/videos/', verbose_name='Видео'),
        ),
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('architecture', 'Архитектура'), ('interiors', 'Интерьеры'), ('concepts', 'Концепты')], default='architecture', max_length=50, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='project',
            name='category_en',
            field=models.CharField(choices=[('architecture', 'Архитектура'), ('interiors', 'Интерьеры'), ('concepts', 'Концепты')], default='architecture', max_length=50, null=True, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='project',
            name='category_ru',
            field=models.CharField(choices=[('architecture', 'Архитектура'), ('interiors', 'Интерьеры'), ('concepts', 'Концепты')], default='architecture', max_length=50, null=True, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='project',
            name='cover',
            field=models.ImageField(upload_to='projects/covers/', verbose_name='Обложка'),
        ),
        migrations.AlterField(
            model_name='project',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description_en',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='project',
            name='location',
            field=models.CharField(blank=True, max_length=200, verbose_name='Локация'),
        ),
        migrations.AlterField(
            model_name='project',
            name='location_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Локация'),
        ),
        migrations.AlterField(
            model_name='project',
            name='location_ru',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Локация'),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Название проекта'),
        ),
        migrations.AlterField(
            model_name='project',
            name='title_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Название проекта'),
        ),
        migrations.AlterField(
            model_name='project',
            name='title_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='Название проекта'),
        ),
        migrations.AlterField(
            model_name='project',
            name='year',
            field=models.PositiveIntegerField(verbose_name='Год'),
        ),
    ]
